"""rename token column

Revision ID: 21404eb49663
Revises: eceb73a3cc76
Create Date: 2024-07-22 23:13:45.464867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21404eb49663'
down_revision: Union[str, None] = 'eceb73a3cc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('value', sa.String(), nullable=False))
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.create_index(op.f('ix_tokens_value'), 'tokens', ['value'], unique=True)
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tokens_value'), table_name='tokens')
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=True)
    op.drop_column('tokens', 'value')
    # ### end Alembic commands ###
